"use client"
import styled from '@emotion/styled';
import { Global } from '@emotion/react';
import { globalStyles } from '@/styles/globals';
import { colors } from '@/styles/colors'
import { Josefin_Sans } from 'next/font/google';
import { Metadata } from 'next';
import { Provider } from 'react-redux';
import {store} from '@/model/store';
import {ThemeProvider} from '@emotion/react';
import {theme} from '@/styles/theme'

export const metadata:Metadata = {
  title: 'Todo List',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <Provider store={store}>
          {/*Подключаем стили для обнуления браузерных*/}
          <Global styles={globalStyles}/>
          <body className={JosefinSans.className}>
            {/*Добавляем стилизованый шаблон,в нём будут храниться страницы*/}
            <Layout>
              {children}
            </Layout>
          </body>
        </Provider>
      </ThemeProvider>
    </html>
  )
}

//fonts

const JosefinSans = Josefin_Sans({subsets:['latin']});

const Layout = styled.div`
  display:flex;
  flex-direction:row;
  justify-content:center;
  align-items:center;
  height:100vh;
  background-color:${colors.layoutGreen};
  background-image: url('/images/background.jpg');
  background-repeat:no-repeat;
  background-size:cover;


`
